#!/bin/bash

if [ "$#" -ge 1 ]; then
    LINK="$1"
else
    echo "No parameters provided."
    exit 1
fi

cache_path=.cache/prodinfo

# Verifica se o diretório não existe
if [ ! -d "$cache_path" ]; then
    # Cria o diretório se não existir
    mkdir -p "$cache_path"
fi

cd $cache_path

curl -i -L $LINK | sed -n '0,/Set-Cookie: \([^;]*\)/ s//\1/p' > cookie.txt

curl -c cookie.txt -L $LINK > content.txt

cat content.txt | sed -n '/<tr id="Item + [0-9]">/,/<\/tr>/p' | sed -n 's/.*<span class="txtTit">\([^<]*\)<\/span>.*/\1/p' > names.txt

cat content.txt | sed -n '/<tr id="Item + [0-9]">/,/<\/tr>/p' | sed -n '/<span class="Rqtd">/,/<\/span>/p' | sed -n 's/.*<strong>Qtde.:<\/strong>\([^<]*\)<\/span>/\1/p' | sed 's/^[^0-9,.]*//; s/,/./g' > qtd.txt

cat content.txt | sed -n '/<tr id="Item + [0-9]">/,/<\/tr>/p' | sed -n '/<span class="RUN">/,/<\/span>/p' | sed -n 's/.*<strong>UN: <\/strong>\([^<]*\)<\/span>/\1/p' > unidade.txt

cat content.txt | sed -n '/<tr id="Item + [0-9]">/,/<\/tr>/p' | sed -n '/<span class="RvlUnit">/,/<\/span>/p' | sed -n 's/.*<strong>Vl. Unit.:<\/strong>\([^<]*\)<\/span>/\1/p' | sed 's/^[^0-9,.]*//; s/,/./g' > valor_unidade.txt
